image: maven:3.9.6-amazoncorretto-17
stages:
  - test
  - deploy


cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - .m2/repository/


before_script:
  # Copy settings.xml from runner into current docker container (/m2 is a mounted directory)
  - cp /m2/settings.xml ~/.m2/settings.xml
  # Sets Version variables for use in job steps and updates pom to correct version for run
  - DEPLOY_REPO=https://nexus.inovexcorp.com/nexus/content/repositories/foundry-maven-dev-hosted/ # Sets default repo to deploy to dev repo


################################################################################
## Runs the maven build, to validate tests pass...
################################################################################
run_maven_build:
  stage: test
  only:
    - merge_requests
  script:
    - mvn $MAVEN_CLI_OPTS clean install -Prun-its
  artifacts:
    expire_in: 4 hrs
    paths:
      - "*/target/it/target/*"
  retry: 1
