/*
 *
 *   owl-orm: A Maven Plugin and API for working with POJOs representing ontological classes on top of RDF4j
 *   Copyright (c) 2024 RealmOne (https://realmone.com/)
 *
 *   Licensed under the MIT License
 */
package com.realmone.maven;

import com.realmone.owl.orm.OrmException;
import com.realmone.owl.orm.generate.OntologyMeta;
import com.realmone.owl.orm.generate.SourceGenerator;
import org.apache.maven.model.Resource;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.Component;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.project.MavenProject;
import org.eclipse.rdf4j.model.ModelFactory;
import org.eclipse.rdf4j.model.impl.DynamicModelFactory;

import java.io.File;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

@Mojo(name = "generate-orm", threadSafe = true)
public class GeneratorMojo extends AbstractMojo {

    private static final ModelFactory MODEL_FACTORY = new DynamicModelFactory();

    @Parameter(alias = "generates", required = true)
    private List<Ontology> generates;

    /**
     * List of reference ontologies.
     */
    @Parameter(alias = "references")
    private List<Ontology> references;

    /**
     * The location where the generated source will be stored.
     */
    @Parameter(property = "outputLocation", required = true,
            defaultValue = "${project.basedir}/target/generated-sources")
    private String outputLocation;

    @Parameter(property = "enforceFullClosure", required = true, defaultValue = "true")
    private boolean enforceFullClosure;

    @Parameter(property = "isolateGenerationClosures", required = true, defaultValue = "false")
    private boolean isolateGenerationClosures;

    /**
     * The Maven project, injected automatically. Used to register the generated-sources
     * directory as a resource directory so that META-INF/services files are included in the JAR.
     */
    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    private MavenProject project;


    @Override
    public void execute() throws MojoExecutionException, MojoFailureException {
        try {
            ensureDirectoryExists(outputLocation);
            SourceGenerator generator = SourceGenerator.builder()
                    .enforceFullClosure(enforceFullClosure)
                    .isolateGenerationClosures(isolateGenerationClosures)
                    .generateForOntologies(convertOnts(generates))
                    .referenceOntologies(convertOnts(references))
                    .outputLocation(outputLocation)
                    .build();
            generator.run();

            // Register outputLocation as a resource directory so that META-INF/services/
            // files generated by the SourceGenerator are included in the JAR by Maven's
            // resource processing (and picked up by maven-bundle-plugin for OSGi bundles).
            Resource resource = new Resource();
            resource.setDirectory(outputLocation);
            resource.addInclude("META-INF/**");
            project.addResource(resource);

        } catch (OrmException e) {
            throw new MojoFailureException("Issue occurred generating source for OWL ORM API", e);
        }
    }

    private static Set<OntologyMeta> convertOnts(List<Ontology> ontologies) {
        return ontologies != null ? ontologies.stream().map(GeneratorMojo::fromOnt).collect(Collectors.toSet())
                : Collections.emptySet();
    }

    private static OntologyMeta fromOnt(Ontology ont) {
        String name = ont.getOntologyName();
        if (name == null || name.isEmpty()) {
            // Derive ontology name from the file path (e.g., "/path/to/foaf.owl" -> "foaf")
            String file = ont.getOntologyFile();
            String baseName = file.contains("/") ? file.substring(file.lastIndexOf('/') + 1) : file;
            name = baseName.contains(".") ? baseName.substring(0, baseName.lastIndexOf('.')) : baseName;
        }
        return OntologyMeta.builder()
                .file(ont.getOntologyFile())
                .ontologyName(name)
                .packageName(ont.getOutputPackage())
                .build();
    }

    private static void ensureDirectoryExists(String outputLocation) {
        File f = new File(outputLocation);
        if (!f.isDirectory() && (!f.mkdirs())) {
            throw new OrmException("Couldn't generate output directory: " + outputLocation);
        }
    }
}
