/*
 *
 *   owl-orm: A Maven Plugin and API for working with POJOs representing ontological classes on top of RDF4j
 *   Copyright (c) 2024 RealmOne (https://realmone.com/)
 *
 *   Licensed under the MIT License
 */
package com.realmone.owl.orm.basic;

import com.realmone.owl.orm.Thing;
import com.realmone.owl.orm.TypeMetadata;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NonNull;
import org.eclipse.rdf4j.model.IRI;

import java.util.Collections;
import java.util.Set;

/**
 * A simple implementation of {@link TypeMetadata} that stores the type information
 * provided at construction time. This class is immutable and thread-safe.
 * <p>
 * Instances of this class can be created either programmatically using the builder,
 * or generated by the code generator alongside the Thing interfaces.
 *
 * @param <T> The type of {@link Thing} this metadata describes
 */
@Builder
@Getter
@EqualsAndHashCode
public class SimpleTypeMetadata<T extends Thing> implements TypeMetadata<T> {

    /**
     * The Java interface class that this metadata describes.
     */
    @NonNull
    private final Class<T> type;

    /**
     * The RDF type IRI that identifies instances of this type.
     */
    @NonNull
    private final IRI typeIRI;

    /**
     * The set of parent type IRIs in the OWL class hierarchy.
     * This is an unmodifiable set.
     */
    @NonNull
    private final Set<IRI> parentTypeIRIs;

    /**
     * Creates a new SimpleTypeMetadata with the given values.
     * The parentTypeIRIs set will be wrapped in an unmodifiable set.
     *
     * @param type           The Java interface class
     * @param typeIRI        The RDF type IRI
     * @param parentTypeIRIs The set of parent type IRIs (will be made unmodifiable)
     */
    public SimpleTypeMetadata(Class<T> type, IRI typeIRI, Set<IRI> parentTypeIRIs) {
        this.type = type;
        this.typeIRI = typeIRI;
        this.parentTypeIRIs = parentTypeIRIs != null
                ? Collections.unmodifiableSet(parentTypeIRIs)
                : Collections.emptySet();
    }

    @Override
    public String toString() {
        return "SimpleTypeMetadata{" +
                "type=" + type.getName() +
                ", typeIRI=" + typeIRI +
                ", parentCount=" + parentTypeIRIs.size() +
                '}';
    }
}
